<?php
$replace = array(
    'AP' => 'AP', //confusion (Advance Placement?)
    'Ac' => 'Accounts',
    'Aministrator' => 'Administrator',
    'ADT' => 'Audit', //confusion
    'Art' => 'Arts',
    'ART' => 'Arts',
    'ARt' => 'Arts',
    'ARTS' => 'Arts',
    'Asst' => 'Assistant',
    'Ass' => 'Assistant',
    'Assit' => 'Assistant',
    'Asistant' => 'Assistant',
    'Assisnat' => 'Assistant',
    'Assisstant' => 'Assistant',
    'Assistan' => 'Assistant',
    'Assstant' => 'Assistant',
    'Asso' => 'Associate',
    'Assoc' => 'Associate',
    'Asscoiate' => 'Associate',
    'ASSOCIATE' => 'Associate',
    'BS' => 'Business School',
    'Burser' => 'Bursar',
    'B/S' => 'Business School',
    'Bs' => 'Business School',
    'BIo' => 'Biology',
    'Bio' => 'Biology',
    'BUS' => 'Business',
    'Bus' => 'Business',
    'Chem' => 'Chemistry',
    'CHem' => 'Chemistry',
    'Citi' => 'Citizenship',
    'Creat' => 'Creative',
    'Chemistrry' => 'Chemistry',
    'COmputing' => 'Computing',
    'Comp' => 'Computer',
    'Com' => 'Computer',
    'Compu' => 'Computing',
    'Cimmunications' => 'Communications',
    'DT' => 'Design and Technology',
    'Dt' => 'Design and Technology',
    'D2D' => 'Day To Day',
    'Dep' => 'Deputy',
    'Deputh' => 'Deputy',
    'ECO' => 'Economics',
    'Econ' => 'Economics',
    'Econo' => 'Economics',
    'EC' => 'Economics',
    'EAL' => 'EAL', //confusion
    'Eco' => 'Economics',
    'Eng' => 'English',
    'ENG' => 'English',
    'Englis' => 'English',
    'Englsih' => 'English',
    'Exp' => 'Expressive',
    'Exe' => 'Executive',
    'Ext' => 'Ext', //confusion
    'Fre' => 'French',
    'FOOD' => 'Food',
    'FOod' => 'Food',
    'Geo' => 'Geography',
    'GEO' => 'Geography',
    'GEo' => 'Geography',
    'Germ' => 'German',
    'Gov' => 'Government',
    'HEAD' => 'Head',
    'HEADS' => 'Head',
    'Heads' => 'Head',
    "Heads'" => 'Head',
    "Head's" => 'Head',
    "Headmaster" => 'Head Master',
    'headteacher' => 'Head Teacher',
    'Headteacher' => 'Head Teacher',
    "Headteacher's" => 'Head Teacher',
    'Hist' => 'History',
    'His' => 'History',
    'Histroy' => 'History',
    'HIST' => 'History',
    'Hum' => 'Humanities',
    'HUm' => 'Humanities',
    'HUM' => 'Humanities',
    'Humaniies' => 'Humanities',
//    'HOF' => 'HOD', //confusion
    'HID' => 'HOD',
    'Hod' => 'HOD',
    'hod' => 'HOD',
    'HR' => 'Human Resource',
    'Hr' => 'Human Resource',
    'ICT' => 'Information Communication Technology',
    'ICt' => 'Information Communication Technology',
    'IT' => 'Information Technology',
    'LTS' => 'Long Term Support',
    'Languaes' => 'Languages',
    'Maths' => 'Math',
    'MAths' => 'Math',
    'MEdia' => 'Media',
    'Medi' => 'Medicine',
    'Med' => 'Medicine',
    'MUSIC' => 'Music',
    'MUS' => 'Music',
    'Mus' => 'Music',
    'MFL' => 'Modern Foreign Languages',
    'PA' => 'Personal Assistant',
    'P/A' => 'Personal Assistant',
    'PE' => 'Physical Education',
    'Pe' => 'Physical Education',
    'Pol' => 'Politics',
    'Polo' => 'Politics',
    'Poli' => 'Politics',
    'PSHE' => 'PSHE', //confusion
    'Pshe' => 'PSHE', //confusion
    'PHSE' => 'PHSE', //confusion
    'Perf' => 'Performing',
    'Perfoming' => 'Performing',
    'Pefroming' => 'Performing',
    'PERF' => 'Performing',
    'PSY' => 'Psychology',
    'Psy' => 'Psychology',
    'PD' => 'PD', //confusion
    'Psyc' => 'Psychology',
    'Psyschology' => 'Psychology',
    'Phy' => 'Physics',
    'PHY' => 'Physics',
    'PHy' => 'Physics',
    'Principals' => 'Principal',
    'Principle' => 'Principal',
    'Prin' => 'Principal',
    'Perm' => 'Permanent',
    'PERM' => 'Permanent',
    'P' => 'Professor',
    'RE' => 'Real Estate', //confusion
    'Re' => 'Real Estate', //confusion
    'RM' => 'Resistant Materials', //confusion
    'REC' => 'Recruitment',
    'Rec' => 'Recruitment',
    'rec' => 'Recruitment',
    'RS' => 'RS', //confusion
    'Sci' => 'Science',
    'SCI' => 'Science',
    'Sciecnce' => 'Science',
    'Scienece' => 'Science',
    'Sciences' => 'Science',
    'Soc' => 'Sociology',
    'SC' => 'Social Care',
    'Spa' => 'Spanish',
    'SPAN' => 'Spanish',
    'Span' => 'Spanish',
    'SLT' => '', //confusion
    'SVP' => 'Senior Vice President', //confusion
    'STEM' => 'STEM', //confusion
    'SENCO' => 'Senco',
    'SENCo' => 'Senco',
    'SENDCo' => 'Senco',
    'SENDCO' => 'Senco',
    'Tech' => 'Technology',
    'TECH' => 'Technology',
    'TEACHER' => 'Teacher',
    'Tecaher' => 'Teacher',
    'Texties' => 'Textiles',
    'Text' => 'Textiles',

    'VP' => 'Vice Principal',
    'Vis' => 'Visual',

);
$combined = array(
    "\Rec" => "Rec",
    "Acting Assistant Head Teacher" => "Acting Assistant Head Teacher",
    "Acting Asst Head" => "Acting Asst Head",
    "Acting Deputy Head" => "Acting Deputy Head",
    "Acting Deputy Principal" => "Acting Deputy Principal",
    "Acting Head Teacher" => "Acting Head Teacher",
    "Acting Head" => "Acting Head",
    "Acting Headteacher" => "Acting Headteacher",
    "Acting HOD Art/DT" => "Acting HOD Art & Acting HOD DT",
    "Acting HOD BS & ECO" => "Acting HOD BS & Acting HOD ECO",
    "Acting HOD Eng" => "Acting HOD Eng",
    "Acting HOD Fre" => "Acting HOD Fre",
    "Acting HOD French" => "Acting HOD French",
    "Acting HOD Geo" => "Acting HOD Geo",
    "Acting HOD Hist" => "Acting HOD Hist",
    "Acting HOD Maths" => "Acting HOD Maths",
    "Acting HOD MFL" => "Acting HOD MFL",
    "Acting HOD Mus" => "Acting HOD Mus",
    "Acting HOD RE" => "Acting HOD RE",
    "Acting HOD Sci" => "Acting HOD Sci",
    "Acting HOD Science" => "Acting HOD Science",
    "Acting Principal" => "Acting Principal",
    "Acting VP & HOD Maths" => "Acting VP & HOD Maths",
    "Acting VP" => "Acting VP",
    "Admin (REC)" => "Admin & REC",
    "Admin" => "Admin",
    "All Recruitment" => "All Recruitment",
    "AP" => "AP",
    "Art & Design HOD" => "HOD Art & HOD Design",
    "Art & DT HOD" => "HOD Art & HOD DT",
    "Art HOD" => "Art HOD",
    "Asistant Head" => "Asistant Head",
    "Ass Ass Head" => "Asso Ass Head",
    "Asscoiate Asst Head & HOD Business" => "Asscoiate Asst Head & HOD Business",
    "Assisnat Head & HOD Psy" => "Assisnat Head & HOD Psy",
    "Assisstant Head" => "Assisstant Head",
    "Assistan Head" => "Assistan Head",
    "Assistant & HOD Eng" => "Assistant & HOD Eng",
    "Assistant & HOD Maths" => "Assistant & HOD Maths",
    "Assistant / HOD Art" => "Assistant & HOD Art",
    "Assistant / HOD English" => "Assistant & HOD English",
    "Assistant Bursar" => "Assistant Bursar",
    "Assistant Head & English" => "Assistant Head & HOD English",
    "Assistant Head & Head Of English & Perf Arts" => "Assistant Head & Head Of English & Head Of Perf Arts",
    "Assistant Head & Head Of Sci" => "Assistant Head & Head Of Sci",
    "Assistant Head & HOD Art" => "Assistant Head & HOD Art",
    "Assistant Head & HOD BS & ECO" => "Assistant Head & HOD BS & HOD ECO",
    "Assistant Head & HOD BS" => "Assistant Head & HOD BS",
    "Assistant Head & HOD Bus & Maths" => "Assistant Head & HOD Bus & HOD Maths",
    "Assistant Head & HOD Business" => "Assistant Head & HOD Business",
    "Assistant Head & HOD Comp & ICT" => "Assistant Head & HOD Comp & HOD ICT",
    "Assistant Head & HOD Creative Arts" => "Assistant Head & HOD Creative Arts",
    "Assistant Head & HOD Dance" => "Assistant Head & HOD Dance",
    "Assistant Head & HOD Drama" => "Assistant Head & HOD Drama",
    "Assistant Head & HOD DT" => "Assistant Head & HOD DT",
    "Assistant Head & HOD Eng & MFL" => "Assistant Head & HOD Eng & HOD MFL",
    "Assistant Head & HOD Eng" => "Assistant Head & HOD Eng",
    "Assistant Head & HOD English" => "Assistant Head & HOD English",
    "Assistant Head & HOD Exp Arts" => "Assistant Head & HOD Exp Arts",
    "Assistant Head & HOD Hist" => "Assistant Head & HOD Hist",
    "Assistant Head & HOD HUM" => "Assistant Head & HOD HUM",
    "Assistant Head & HOD Hum" => "Assistant Head & HOD Hum",
    "Assistant Head & HOD ICT" => "Assistant Head & HOD ICT",
    "Assistant Head & HOD Math" => "Assistant Head & HOD Math",
    "Assistant Head & HOD Math, BS & ICT" => "Assistant Head & HOD Math & HOD BS & HOD ICT",
    "Assistant Head & HOD Maths" => "Assistant Head & HOD Maths",
    "Assistant Head & HOD Medi" => "Assistant Head & HOD Medi",
    "Assistant Head & HOD MFL" => "Assistant Head & HOD MFL",
    "Assistant Head & HOD Mus" => "Assistant Head & HOD Mus",
    "Assistant Head & HOD PE" => "Assistant Head & HOD PE",
    "Assistant Head & HOD Physics" => "Assistant Head & HOD Physics",
    "Assistant Head & HOD PSHE" => "Assistant Head & HOD PSHE",
    "Assistant Head & HOD RE" => "Assistant Head & HOD RE",
    "Assistant Head & HOD Sci" => "Assistant Head & HOD Sci",
    "Assistant Head & HOF Creative Arts" => "Assistant Head & HOF Creative Arts",
    "Assistant Head & HOF Hum & HOD Hist" => "Assistant Head & HOF Hum & HOD Hist",
    "Assistant Head & HOF Sci" => "Assistant Head & HOF Sci",
    "Assistant Head & HOF STEM" => "Assistant Head & HOF STEM",
    "Assistant Head & HOF Tech & ICT" => "Assistant Head & HOF Tech & HOF ICT",
    "Assistant Head & Maths" => "Assistant Head & HOD Maths",
    "Assistant Head & MFL" => "Assistant Head & HOD MFL",
    "Assistant Head & Music" => "Assistant Head & HOD Music",
    "Assistant Head & Science" => "Assistant Head & HOD Science",
    "Assistant Head & SENCO" => "Assistant Head & SENCO",
    "Assistant Head & Senco" => "Assistant Head & Senco",
    "Assistant Head &HOD Art" => "Assistant Head & HOD Art",
    "Assistant Head &Maths" => "Assistant Head & HOD Maths",
    "Assistant Head (LTS)" => "Assistant Head & LTS",
    "Assistant Head (Maternity Leave)" => "Assistant Head & Maternity Leave",
    "Assistant Head (REC)" => "Assistant Head & REC",
    "Assistant Head (Staff Rec)" => "Assistant Head & Staff Rec",
    "Assistant Head / English" => "Assistant Head & HOD English",
    "Assistant Head / Science" => "Assistant Head & HOD Science",
    "Assistant Head Teacher & HOD Comp Sci" => "Assistant Head Teacher & HOD Comp Sci",
    "Assistant Head Teacher & HOD Maths" => "Assistant Head Teacher & HOD Maths",
    "Assistant Head Teacher (Maternity)" => "Assistant Head Teacher & Maternity",
    "Assistant Head Teacher" => "Assistant Head Teacher",
    "Assistant Head" => "Assistant Head",
    "Assistant Head/ REC" => "Assistant Head & REC",
    "Assistant Head/English" => "Assistant Head & HOD English",
    "Assistant Head/HOD RE" => "Assistant Head/HOD RE",
    "Assistant Head/MFL" => "Assistant Head & HOD MFL",
    "Assistant Head/Rec" => "Assistant Head & Rec",
    "Assistant Head/Senco" => "Assistant Head & Senco",
    "Assistant Head/SENDCo" => "Assistant Head/SENDCo",
    "Assistant Headteacher & HOD Geo" => "Assistant Head Teacher & HOD Geo",
    "Assistant Headteacher & Maths" => "Assistant Head Teacher & Maths",
    "Assistant Headteacher & Science" => "Assistant Head Teacher & Science",
    "Assistant Headteacher And SENCO" => "Assistant Headteacher & SENCO",
    "Assistant Headteacher" => "Assistant Headteacher",
    "Assistant Headteacher/SENCo" => "Assistant Headteacher & HOD SENCo",
    "Assistant Headteacher/Senco" => "Assistant Headteacher & Senco",
    "Assistant Headteacher​" => "Assistant Headteacher",
    "Assistant PA To SLT" => "Assistant PA To SLT",
    "Assistant Principal & HOD Eng" => "Assistant Principal & HOD Eng",
    "Assistant Principal & HOD MFL" => "Assistant Principal & HOD MFL",
    "Assistant Principal & HOD Music" => "Assistant Principal & HOD Music",
    "Assistant Principal & SENCO" => "Assistant Principal & SENCO",
    "Assistant Principal / SENCO" => "Assistant Principal & SENCO",
    "Assistant Principal" => "Assistant Principal",
    "Assistant Principals (Recruitment)" => "Assistant Principals & Recruitment",
    "Assistant Principals - Head Of Sixth Form" => "Assistant Principal & Head Of Sixth Form",
    "Assistant Principals" => "Assistant Principals",
    "Assistant To Bursar (REC)" => "Bursar Assistant & REC",
    "Assistant Vice Principal & HOD ICT" => "Assistant Vice Principal & HOD ICT",
    "Assistant Vice Principal & HOD Sci" => "Assistant Vice Principal & HOD Sci",
    "Assistant Vice Principal" => "Assistant Vice Principal",
    "Assistant" => "Assistant",
    "Assitant Head" => "Assitant Head",
    "Asso Asst Head" => "Asso Asst Head",
    "Assoc Asst Head & HOD BS & Eco" => "Assoc Asst Head & HOD BS & HOD Eco",
    "Assoc Asst Head & HOD Hist" => "Assoc Asst Head & HOD Hist",
    "Assoc Asst Head & HOD PE" => "Assoc Asst Head & HOD PE",
    "Assoc Asst Head & HOD RE" => "Assoc Asst Head & HOD RE",
    "Assoc Asst Head & HOF Hum" => "Assoc Asst Head & HOF Hum",
    "Assoc Asst Head & MFL" => "Associate Assistant Head & HOD MFL",
    "Assoc Asst Head" => "Assoc Asst Head",
    "Assoc Head" => "Assoc Head",
    "Assoc Iate Asst Head" => "Associate Asst Head",
    "Associate Assistant Headteacher" => "Associate Assistant Headteacher",
    "Associate Assistant Principal" => "Associate Assistant Principal",
    "Associate Assit Head" => "Associate Assit Head",
    "Associate Asst Head & HOD Sci" => "Associate Asst Head & HOD Sci",
    "Associate Asst Head" => "Associate Asst Head",
    "Associate Deputy Head" => "Associate Deputy Head",
    "Associate Head & HOD Dance" => "Associate Head & HOD Dance",
    "Associate Head & HOD PE" => "Associate Head & HOD PE",
    "Associate Head & HOD Spanish" => "Associate Head & HOD Spanish",
    "ASSOCIATE HEAD TEACHER" => "ASSOCIATE HEAD TEACHER",
    "Associate Head" => "Associate Head",
    "Associate P & HOD Geo" => "Associate P & HOD Geo",
    "Associate P" => "Associate P",
    "Associate Principal" => "Associate Principal",
    "Associate SLT Member & HOD Sci" => "Associate SLT Member & HOD Sci",
    "Associate SLT Member" => "Associate SLT Member",
    "Associate SLT Member/Geography" => "Associate SLT Member & HOD Geography",
    "Assstant" => "Assstant",
    "AVP" => "AVP",
    "BS Manager" => "BS Manager",
    "Bursar (REC)" => "Bursar & REC",
    "Bursar / Recruitment" => "Bursar & Recruitment",
    "Bursar" => "Bursar",
    "Burser Deals With Rec" => "Burser & Rec",
    "Burser" => "Burser",
    "Bus HOD" => "Bus HOD",
    "Bus Manager" => "Bus Manager",
    "Business Manager & Rec Person" => "Business Manager & Rec",
    "Business Manager (Perm Rec)" => "Business Manager & Rec",
    "Business Manager (REC Person)" => "Business Manager & REC",
    "Business Manager (REC)" => "Business Manager & REC",
    "Business Manager - REC" => "Business Manager & REC",
    "Business Manager" => "Business Manager",
    "Business Manager/Recruitment" => "Business Manager & Recruitment",
    "Business" => "Business",
    "CEO Trust" => "CEO Trust",
    "CEO Unity Schools Trust / Executive Head" => "CEO Unity Schools Trust & Executive Head",
    "CEO" => "CEO",
    "CEO, Riverston Schools" => "CEO Riverston Schools",
    "CO Head" => "CO Head",
    "Co Heads" => "Co Heads",
    "Co-Assistant Principal" => "Co-Assistant Principal",
    "Co-Head Teacher" => "Co-Head Teacher",
    "Company Secretary" => "Company Secretary",
    "Cover & Finance Manager" => "Cover & Finance Manager",
    "Cover & HR Assistant" => "Cover & HR Assistant",
    "Cover + LTS" => "Cover & LTS",
    "Cover And REC" => "Cover And REC",
    "Cover Manager" => "Cover Manager",
    "Cover" => "Cover",
    "Curriculum PA" => "Curriculum PA",
    "D2D" => "D2D",
    "Day To Day" => "Day To Day",
    "Deals With Rec (HR)" => "Rec & HR",
    "Deals With Rec" => "Rec",
    "Deals With Recruitment" => "Recruitment",
    "Dep Rec" => "Dep Rec",
    "Deputh Head" => "Deputh Head",
    "Deputy + Rec" => "Deputy & Rec",
    "Deputy Asst Head & HOF DT & Art" => "Deputy Asst Head & HOF DT & HOF Art",
    "Deputy Head & HOD Eng" => "Deputy Head & HOD Eng",
    "Deputy Head & HOD English" => "Deputy Head & HOD English",
    "Deputy Head & HOD English, Media & MFL" => "Deputy Head & HOD English & HOD Media & HOD MFL",
    "Deputy Head & HOD Geo" => "Deputy Head & HOD Geo",
    "Deputy Head & HOD Geography" => "Deputy Head & HOD Geography",
    "Deputy Head & HOD Math & Computing" => "Deputy Head & HOD Math & HOD Computing",
    "Deputy Head & HOD MFL" => "Deputy Head & HOD MFL",
    "Deputy Head & HOD RE" => "Deputy Head & HOD RE",
    "Deputy Head & HOD RS" => "Deputy Head & HOD RS",
    "Deputy Head & HOF Cimmunications" => "Deputy Head & HOF Cimmunications",
    "Deputy Head (REC)" => "Deputy Head & REC",
    "Deputy Head - English" => "Deputy Head & HOD English",
    "Deputy Head - Rec" => "Deputy Head & Rec",
    "Deputy Head Teacher" => "Deputy Head Teacher",
    "Deputy Head" => "Deputy Head",
    "Deputy Head, Teaching And Learning:" => "Deputy Head & Deputy Teaching & Deputy Learning", //check this
    "Deputy Head/Recruitment" => "Deputy Head & Recruitment",
    "Deputy Heads' PA" => "Deputy Heads PA",
    "Deputy Headteacher (Acting HOD Bus)" => "Deputy Headteacher & Acting HOD Bus",
    "Deputy Headteacher" => "Deputy Headteacher",
    "Deputy Principal" => "Deputy Principal",
    "Deputy" => "Deputy",
    "Director Of Art & Design" => "HOD Art & Design",
    "Director Of Business Development" => "Director Of Business Development",
    "Director Of Creative & Performing Arts" => "HOD Creative Arts & HOD Performing Arts",
    "Director Of Formation" => "Director Of Formation",
    "Director Of Humanities" => "Director Of Humanities",
    "Director Of Humanities, Languages And English" => "HOD Humanities & HOD Languages & HOD English",
    "Director Of Learning" => "Director Of Learning",
    "Director Of Music" => "Director Of Music",
    "Director Of PE" => "Director Of PE",
    "Director Of Performing Arts" => "Director Of Performing Arts",
    "Director Of Science" => "Director Of Science",
    "Director Of Science, Technology, Engineering And Maths" => "HOD Science & HOD Technology & HOD Engineering & HOD Maths",
    "Director Of Sport" => "Director Of Sport",
    "Director Of Sports" => "Director Of Sports",
    "Director Of Staff" => "Director Of Staff",
    "Director Of Studies" => "Director Of Studies",
    "Drama HOD" => "HOD Drama",
    "Eng HOD" => "HOD Eng",
    "English HOD" => "HOD English",
    "Exe PA" => "Exe PA",
    "Executive Assistant" => "Executive Assistant",
    "Executive Head Teacher" => "Executive Head Teacher",
    "Executive Head" => "Executive Head",
    "Executive Principal" => "Executive Principal",
    "Executive Principle" => "Executive Principle",
    "Finance And Business Manager" => "Finance And Business Manager",
    "Finance" => "HOD Finance",
    "General" => "HOD General",
    "GEO HOD" => "HOD Geo",
    "Geo HOD" => "HOD Geo",
    "Head & Chief Executive" => "Head & Chief Executive",
    "Head & Deputy Head PA" => "Head & Deputy Head PA",
    "Head (maternity)" => "Head & maternity",
    "Head / Recruitment" => "Head & Recruitment",
    "Head Aquila" => "Head Aquila",
    "Head College VI" => "Head College VI",
    "Head Master" => "Head Master",
    "Head Of Academy" => "Head Of Academy",
    "Head Of School" => "Head Of School",
    "Head Of Secondary School" => "Head Of Secondary School",
    "Head Of Senior School & HOD HIST" => "Head Of Senior School & HOD HIST",
    "Head Of Senior School" => "Head Of Senior School",
    "Head Of Senior" => "Head Of Senior",
    "Head Of Seniors" => "Head Of Seniors",
    "Head Of Upper" => "Head Of Upper",
    "Head Of Visual & Performing Arts" => "Head Of Visual Arts & Head Of Performing Arts",
    "Head Orion" => "Head Orion",
    "Head P/A" => "Head PA",
    "Head PA (LTS)" => "Head PA & LTS",
    "Head PA (PERM)" => "Head PA & PERM",
    "Head PA (REC)" => "Head PA & REC",
    "Head PA (Rec)" => "Head PA & Rec",
    "Head PA - Rec Person" => "Head PA & Rec",
    "Head PA / Office Manager" => "Head PA & Office Manager",
    "Head PA" => "Head PA",
    "Head Pa" => "PA",
    "Head Pegasus" => "Head Pegasus",
    "Head Phoenix" => "Head Phoenix",
    "Head Teacher (REC)" => "Head Teacher & REC",
    "Head Teacher" => "Head Teacher",
    "Head Tecaher" => "Head Tecaher",
    "HEAD" => "HEAD",
    "Head" => "Head",
    "Head's PA" => "Head PA",
    "Headmaster" => "Headmaster",
    "Heads P/A & HR Manager" => "Heads P/A & HR Manager",
    "Heads P/A & HR" => "Heads P/A & HR",
    "Heads P/A (HR)" => "Heads PA & HR",
    "Heads P/A (Rec)" => "Heads P/A & Rec",
    "Heads P/A (REC)" => "Heads P/A & REC",
    "Heads P/A - Rec" => "Heads P/A & Rec",
    "Heads P/A" => "PA",
    "Heads PA & HR" => "Heads PA & HR",
    "Heads PA & Office Manager" => "Heads PA & Office Manager",
    "Heads PA & REC" => "Heads PA & REC",
    "Heads PA (REC)" => "Heads PA & REC",
    "Heads PA - Helps With Recruitment" => "Heads PA & Recruitment",
    "Heads PA - Perm Recruitment" => "Heads PA & Perm Recruitment",
    "Heads PA - Perm" => "PA",
    "Heads PA - Rec" => "Heads PA & Rec",
    "Heads PA / HR" => "Heads PA & HR",
    "Heads PA And Cover" => "Heads PA And Cover",
    "Heads PA REC" => "Heads PA REC",
    "HEADS PA" => "HEADS PA",
    "Heads PA" => "Heads PA",
    "Heads Pa" => "Heads Pa",
    "Heads PA/HR" => "Heads PA & HR",
    "Heads" => "Heads",
    "Headteacher" => "Headteacher",
    "Headteacher's PA" => "Headteacher's PA",
    "Hed PA" => "Hed PA",
    "HID Hist" => "HID Hist",
    "HIST HOD" => "HOD HIST",
    "Hist HOD" => "HOD Hist",
    "HOD Ac, BS, Eco & IT" => "HOD Ac & HOD BS & HOD Eco & HOD IT",
    "HOD Art & Design / Photography" => "HOD Art & HOD Design & HOD Photography",
    "HOD Art & Design" => "HOD Art & HOD Design",
    "HOD Art & DT" => "HOD Art & HOD DT",
    "HOD Art & Graphics" => "HOD Art & HOD Graphics",
    "HOD ART & MFL" => "HOD ART & HOD MFL",
    "HOD Art & Photo & Textiles" => "HOD Art & HOD Photo & HOD Textiles",
    "HOD Art & Photo" => "HOD Art & HOD Photo",
    "HOD Art & Photography" => "HOD Art & HOD Photography",
    "HOD Art & Tech" => "HOD Art & HOD Tech",
    "HOD Art & Technology" => "HOD Art & HOD Technology",
    "HOD Art & Textiles" => "HOD Art & HOD Textiles",
    "HOD Art - Point" => "HOD Art & HOD Point",
    "HOD Art / DT" => "HOD Art & HOD DT",
    "HOD Art And Design" => "HOD Art And Design",
    "HOD ART" => "HOD ART",
    "HOD ARt" => "HOD ARt",
    "HOD Art" => "HOD Art",
    "Hod Art" => "Hod Art",
    "HOD Art, Design & Technology" => "HOD Art & HOD Design & HOD Technology",
    "HOD Art, DT & Music" => "HOD Art & HOD DT & HOD Music",
    "HOD Art, DT & Photo" => "HOD Art & HOD DT & HOD Photo",
    "HOD Art, DT & Text" => "HOD Art & HOD DT & HOD Text",
    "HOD Art/DT" => "HOD Art & HOD DT",
    "HOD ARTS" => "HOD ARTS",
    "HOD B/S & Eco" => "HOD B/S & HOD Eco",
    "HOD B/S" => "HOD B/S",
    "HOD BIo" => "HOD BIo",
    "HOD Bio" => "HOD Bio",
    "HOD Biology Joint" => "HOD Biology Joint",
    "HOD Biology" => "HOD Biology",
    "HOD Boys PE" => "HOD Boys PE",
    "HOD Bs & Comp" => "HOD Bs & HOD Comp",
    "HOD BS & Computing" => "HOD BS & HOD Computing",
    "HOD BS & EC" => "HOD BS & HOD EC",
    "HOD BS & ECO" => "HOD BS & HOD ECO",
    "HOD BS & Eco" => "HOD BS & HOD Eco",
    "HOD BS & Economics" => "HOD BS & HOD Economics",
    "HOD BS & Geo" => "HOD BS & HOD Geo",
    "HOD BS & ICT" => "HOD BS & HOD ICT",
    "HOD BS" => "HOD BS",
    "HOD BS& Eco" => "HOD BS & HOD Eco",
    "HOD BS, Comp & ICT" => "HOD BS & HOD Comp & HOD ICT",
    "HOD BS, Eco" => "HOD BS & HOD Eco",
    "HOD Bs, ICT, Comp & Eco, Mus" => "HOD Bs & HOD ICT & HOD Comp & HOD Eco & HOD Mus",
    "HOD Bus & Com Sci" => "HOD Bus & HOD Com Sci",
    "HOD Bus & Comp" => "HOD Bus & HOD Comp",
    "HOD BUS & ECO" => "HOD BUS & HOD ECO",
    "HOD BUS & ICT" => "HOD BUS & HOD ICT",
    "HOD Bus & ICT" => "HOD Bus & HOD ICT",
    "HOD BUS" => "HOD BUS",
    "HOD Bus" => "HOD Bus",
    "HOD Business & Comp / ICT" => "HOD Business & Comp & HOD ICT",
    "HOD Business & COmputing" => "HOD Business & HOD COmputing",
    "HOD Business & Computing" => "HOD Business & HOD Computing",
    "HOD Business & ECO" => "HOD Business & HOD ECO",
    "HOD Business & Eco" => "HOD Business & HOD Eco",
    "HOD Business & Econ" => "HOD Business & HOD Econ",
    "HOD Business & Economics" => "HOD Business & HOD Economics",
    "HOD Business & ICT" => "HOD Business & HOD ICT",
    "HOD Business / Economics / Geography" => "HOD Business & HOD Economics & HOD Geography",
    "HOD Business / Economics" => "HOD Business & HOD Economics",
    "HOD Business And Economics" => "HOD Business And Economics",
    "HOD Business Studies & Economics" => "HOD Business Studies & HOD Economics",
    "HOD Business Studies" => "HOD Business Studies",
    "HOD Business" => "HOD Business",
    "HOD Business, DT And IT" => "HOD Business & HOD DT & HOD IT",
    "HOD Business/Comp" => "HOD Business & HOD Comp",
    "HOD Business/Computing" => "HOD Business & HOD Computing",
    "HOD Business/Eco" => "HOD Business & Eco",
    "HOD Business/Econ" => "HOD Business & HOD Econ",
    "HOD Business/Econo" => "HOD Business & HOD Econo",
    "HOD Business/ICT" => "HOD Business & HOD ICT",
    "HOD Chem & Sci" => "HOD Chem & HOD Sci",
    "HOD CHem" => "HOD CHem",
    "HOD Chem" => "HOD Chem",
    "HOD Chemistrry" => "HOD Chemistrry",
    "HOD Chemistry" => "HOD Chemistry",
    "HOD Child Care" => "HOD Child Care",
    "HOD Citi & Gov & Pol" => "HOD Citi & HOD Gov & HOD Pol",
    "HOD Citi & Pshe" => "HOD Citi & HOD Pshe",
    "HOD Citizenship" => "HOD Citizenship",
    "HOD Citizenship/PSHE" => "HOD Citizenship & HOD PSHE",
    "HOD Classics" => "HOD Classics",
    "HOD Comp & Bus" => "HOD Comp & HOD Bus",
    "HOD Comp & Business" => "HOD Comp & HOD Business",
    "HOD Comp & ICT" => "HOD Comp & HOD ICT",
    "HOD Comp & IT" => "HOD Comp & HOD IT",
    "HOD Comp Sci & ICT" => "HOD Comp Sci & HOD ICT",
    "HOD Comp Sci & Soc" => "HOD Comp Sci & HOD Soc",
    "HOD Comp Sci" => "HOD Comp Sci",
    "HOD Comp Sco" => "HOD Comp Sco",
    "HOD Comp" => "HOD Comp",
    "HOD Computer Science" => "HOD Computer Science",
    "HOD Computing & Business" => "HOD Computing & HOD Business",
    "HOD Computing & Technology" => "HOD Computing & HOD Technology",
    "HOD COmputing" => "HOD COmputing",
    "HOD Computing" => "HOD Computing",
    "HOD Computing, BS & ICT" => "HOD Computing, BS & HOD ICT",
    "HOD Computing/Business" => "HOD Computing & HOD Business",
    "HOD Creat Arts & Art" => "HOD Creat Arts & HOD Art",
    "HOD Creat Arts & Mus" => "HOD Creat Arts & HOD Mus",
    "HOD Creative & Perf Arts" => "HOD Creative & HOD Perf Arts",
    "HOD Creative & Performing Arts" => "HOD Creative & HOD Performing Arts",
    "HOD Creative Arts & Performing Arts" => "HOD Creative Arts & HOD Performing Arts",
    "HOD Creative Arts And Technology" => "HOD Creative Arts & HOD Technology",
    "HOD Creative Arts" => "HOD Creative Arts",
    "HOD Creative Technologies" => "HOD Creative Technologies",
    "HOD Dance" => "HOD Dance",
    "Hod Dance" => "Hod Dance",
    "HOD Design Technology & Art" => "HOD Design Technology & HOD Art",
    "HOD Design Technology" => "HOD Design Technology",
    "HOD Design" => "HOD Design",
    "HOD Digital Technology" => "HOD Digital Technology",
    "HOD Drama & Dance" => "HOD Drama & HOD Dance",
    "HOD Drama & DT" => "HOD Drama & HOD DT",
    "HOD Drama & Eng" => "HOD Drama & HOD Eng",
    "HOD Drama & Music" => "HOD Drama & HOD Music",
    "HOD Drama (Maternity Leave)" => "HOD Drama & Maternity Leave",
    "HOD Drama (Maternity)" => "HOD Drama & Maternity",
    "HOD Drama / Music" => "HOD Drama & HOD Music",
    "HOD Drama Acting" => "HOD Drama & HOD Acting",
    "HOD Drama And Perfoming Arts" => "HOD Drama And Perfoming Arts",
    "HOD Drama" => "HOD Drama",
    "HOD Drama, MFL & Music" => "HOD Drama & HOD MFL & HOD Music",
    "HOD DT & Art & Design" => "HOD DT & HOD Art & HOD Design",
    "HOD DT & ART" => "HOD DT & HOD ART",
    "HOD DT & Art" => "HOD DT & HOD Art",
    "HOD DT & Comp" => "HOD DT & HOD Comp",
    "HOD DT & Computing" => "HOD DT & HOD Computing",
    "HOD DT & PE" => "HOD DT & HOD PE",
    "HOD DT (maternity Leave)" => "HOD DT & maternity Leave",
    "HOD DT Acting" => "HOD DT & HOD Acting",
    "HOD DT And Art" => "HOD DT & HOD Art",
    "HOD DT Food & Textiles Technology" => "HOD DT & HOD Food & HOD Textiles Technology",
    "HOD DT RM & Graphics" => "HOD DT & HOD RM & HOD Graphics",
    "HOD DT" => "HOD DT",
    "HOD Dt" => "HOD Dt",
    "HOD DT, Humanities, IT" => "HOD DT & HOD Humanities & HOD IT",
    "HOD EAL" => "HOD EAL",
    "HOD ECO & BS" => "HOD ECO & HOD BS",
    "HOD Eco & BS" => "HOD Eco & HOD BS",
    "HOD Eco & Bus" => "HOD Eco & HOD Bus",
    "HOD ECO" => "HOD ECO",
    "HOD Eco" => "HOD Eco",
    "HOD Econ & Business" => "HOD Econ & HOD Business",
    "HOD Econ" => "HOD Econ",
    "HOD Econ/Business" => "HOD Econ & HOD Business",
    "HOD Economics" => "HOD Economics",
    "HOD Economics/Business" => "HOD Economics & HOD Business",
    "HOD Electronics" => "HOD Electronics",
    "HOD Eng & Drama Maternity" => "HOD Eng & HOD Drama & Maternity",
    "HOD Eng & Maths" => "HOD Eng & HOD Maths",
    "HOD Eng & Med" => "HOD Eng & HOD Med",
    "HOD ENG (Maternity)" => "HOD ENG & Maternity",
    "HOD ENG" => "HOD ENG",
    "HOD Eng" => "HOD Eng",
    "HOD Engineering & Construction" => "HOD Engineering & HOD Construction",
    "HOD Engineering" => "HOD Engineering",
    "HOD Englis" => "HOD Englis",
    "HOD English & Drama" => "HOD English & HOD Drama",
    "HOD English & Film" => "HOD English & HOD Film",
    "HOD English & Media" => "HOD English & HOD Media",
    "HOD English / Media" => "HOD English & HOD Media",
    "HOD English Acting" => "HOD English Acting",
    "HOD English" => "HOD English",
    "HOD English, Humanities, MFL" => "HOD English & HOD Humanities & HOD MFL",
    "HOD English/ Media & Perf Arts" => "HOD English & HOD Media & HOD Perf Arts",
    "HOD Englsih" => "HOD Englsih",
    "HOD Exp Arts & Music" => "HOD Exp Arts & HOD Music",
    "HOD Exp Arts" => "HOD Exp Arts",
    "HOD Expressive Arts" => "HOD Expressive Arts",
    "HOD Fashion & Textiles" => "HOD Fashion & HOD Textiles",
    "HOD Food & Nutrition" => "HOD Food & HOD Nutrition",
    "HOD Food & Textiles" => "HOD Food & HOD Textiles",
    "HOD FOOD" => "HOD FOOD",
    "HOD FOod" => "HOD FOod",
    "HOD Food" => "HOD Food",
    "HOD Food/Text" => "HOD Food & HOD Text",
    "HOD Food/Texties" => "HOD Food & HOD Texties",
    "HOD Food/Textiles" => "HOD Food & HOD Textiles",
    "HOD For Arts" => "HOD Arts",
    "HOD Fre" => "HOD Fre",
    "HOD French & Spanish" => "HOD French & HOD Spanish",
    "HOD French" => "HOD French",
    "HOD Geo Acting" => "Acting HOD Geo",
    "HOD GEO" => "HOD GEO",
    "HOD GEo" => "HOD GEo",
    "HOD Geo" => "HOD Geo",
    "HOD Geography & RE" => "HOD Geography & HOD RE",
    "HOD Geography Acting" => "Acting HOD Geography",
    "HOD Geography" => "HOD Geography",
    "HOD Germ" => "HOD Germ",
    "HOD German" => "HOD German",
    "HOD Girls PE" => "HOD Girls PE",
    "HOD Gov & Pol" => "HOD Gov & HOD Pol",
    "HOD Gov & Politics" => "HOD Gov & HOD Politics",
    "HOD Gov & Polo" => "HOD Gov & HOD Polo",
    "HOD Government & Politics" => "HOD Government & HOD Politics",
    "HOD Government And Politics" => "HOD Government And Politics",
    "HOD Graphics" => "HOD Graphics",
    "HOD H&SC" => "HOD Health And Social Care",
    "HOD Health & SC" => "HOD Health & HOD SC",
    "HOD Health And Social Care" => "HOD Health And Social Care",
    "HOD His" => "HOD His",
    "HOD Hist & Geo" => "HOD Hist & HOD Geo",
    "HOD Hist & Poli" => "HOD Hist & HOD Poli",
    "HOD Hist / Hum" => "HOD Hist & HOD Hum",
    "HOD HIST" => "HOD HIST",
    "HOD Hist" => "HOD Hist",
    "HOD History & Citizenship" => "HOD History & HOD Citizenship",
    "HOD History & Geo" => "HOD History & HOD Geo",
    "HOD History & Geography" => "HOD History & HOD Geography",
    "HOD History & Hum" => "HOD History & HOD Hum",
    "HOD History & Sociology" => "HOD History & HOD Sociology",
    "HOD History (Maternity Leave)" => "HOD History & Maternity Leave",
    "HOD History And Government & Politics" => "HOD History & HOD Government & HOD Politics",
    "HOD History" => "HOD History",
    "HOD History/Humanities" => "HOD History & HOD Humanities",
    "HOD Histroy" => "HOD Histroy",
    "HOD Hum & Geo" => "HOD Hum & HOD Geo",
    "HOD Hum & MFL" => "HOD Hum & HOD MFL",
    "HOD HUM" => "HOD HUM",
    "HOD HUm" => "HOD HUm",
    "HOD Hum" => "HOD Hum",
    "HOD Humaniies" => "HOD Humaniies",
    "HOD Humanities" => "HOD Humanities",
    "HOD ICT & B/S" => "HOD ICT & HOD BS",
    "HOD ICT & BS" => "HOD ICT & HOD BS",
    "HOD ICT & Bus" => "HOD ICT & HOD Bus",
    "HOD ICT & Business" => "HOD ICT & HOD Business",
    "HOD ICT & Comp" => "HOD ICT & HOD Comp",
    "HOD ICT & Maths" => "HOD ICT & HOD Maths",
    "HOD ICT / Comp & Bus" => "HOD ICT & HOD Comp & HOD Bus",
    "HOD ICT / Maths" => "HOD ICT & HOD Maths",
    "HOD ICT And Business" => "HOD ICT And Business",
    "HOD ICT" => "HOD ICT",
    "HOD ICt" => "HOD ICt",
    "HOD ICT/Computing" => "HOD ICT & HOD Computing",
    "HOD ICT/Technology" => "HOD ICT & HOD Technology",
    "HOD IT & DT" => "HOD IT & HOD DT",
    "HOD Italian" => "HOD Italian",
    "HOD Languages & EAL" => "HOD Languages & HOD EAL",
    "HOD Mandarin" => "HOD Mandarin",
    "HOD Math & Computing" => "HOD Math & HOD Computing",
    "HOD Math & Eco" => "HOD Math & HOD Eco",
    "HOD Math & ICT" => "HOD Math & HOD ICT",
    "HOD Math" => "HOD Math",
    "HOD Math, BS & ICT" => "HOD Math, BS & HOD ICT",
    "HOD Mathematics" => "HOD Mathematics",
    "HOD Maths & Business" => "HOD Maths & HOD Business",
    "HOD Maths & Comp" => "HOD Maths & HOD Comp",
    "HOD Maths & Compu" => "HOD Maths & HOD Compu",
    "HOD Maths & ICT" => "HOD Maths & HOD ICT",
    "HOD Maths & Science" => "HOD Maths & HOD Science",
    "HOD Maths (Joint)" => "HOD Maths",
    "HOD Maths (maternity Leave)" => "HOD Maths & Maternity Leave",
    "HOD Maths Acting" => "HOD Maths Acting",
    "HOD MAths" => "HOD MAths",
    "HOD Maths" => "HOD Maths",
    "Hod Maths" => "Hod Maths",
    "HOD Media & Film" => "HOD Media & HOD Film",
    "HOD Media Studies" => "HOD Media Studies",
    "HOD MEdia" => "HOD MEdia",
    "HOD Media" => "HOD Media",
    "HOD MFL & HOD French" => "HOD MFL & HOD French",
    "HOD MFL (Maternity)" => "HOD MFL & Maternity",
    "HOD MFL / English" => "HOD MFL & HOD English",
    "HOD MFL Acting" => "HOD MFL Acting",
    "HOD MFL" => "HOD MFL",
    "HOD MFl" => "HOD MFl",
    "HOD Mfl" => "HOD Mfl",
    "HOD Mus & Med" => "HOD Mus & HOD Med",
    "HOD MUS" => "HOD MUS",
    "HOD Mus" => "HOD Mus",
    "HOD Music & Art" => "HOD Music & HOD Art",
    "HOD Music & Media" => "HOD Music & HOD Media",
    "HOD MUSIC & MFL" => "HOD MUSIC & HOD MFL",
    "HOD Music" => "HOD Music",
    "HOD PD" => "HOD PD",
    "HOD PE & BS" => "HOD PE & HOD BS",
    "HOD PE & Bus" => "HOD PE & HOD Bus",
    "HOD PE & Dance" => "HOD PE & HOD Dance",
    "HOD PE & H&SC" => "HOD PE & HOD Health & HOD Social Care",
    "HOD PE & Perf Arts" => "HOD PE & HOD Perf Arts",
    "HOD PE (Acting)" => "Acting HOD PE",
    "HOD PE (Boys)" => "HOD Boys PE",
    "HOD PE (Girls)" => "HOD Girls PE",
    "HOD PE Boys" => "HOD Boys PE",
    "HOD PE Girls" => "HOD Girls PE",
    "HOD PE" => "HOD PE",
    "Hod Pe" => "Hod Pe",
    "HOD Pefroming Arts" => "HOD Pefroming Arts",
    "HOD Perf Arts & Mus" => "HOD Perf Arts & HOD Mus",
    "HOD Perf Arts & Music" => "HOD Perf Arts & HOD Music",
    "HOD Perf Arts & PE" => "HOD Perf Arts & HOD PE",
    "HOD Perf Arts (Dance)" => "HOD Perf Arts & Dance",
    "HOD PERF ARTS" => "HOD PERF ARTS",
    "HOD PERF Arts" => "HOD PERF Arts",
    "HOD Perf Arts" => "HOD Perf Arts",
    "HOD Performing & Creative Arts" => "HOD Performing Arts & HOD Creative Arts",
    "HOD Performing Arts" => "HOD Performing Arts",
    "HOD Philosophy And Ethics" => "HOD Philosophy & HOD Ethics",
    "HOD Philosophy" => "HOD Philosophy",
    "HOD Photography" => "HOD Photography",
    "HOD PHSE" => "HOD PHSE",
    "HOD Phy & Soc" => "HOD Phy & HOD Soc",
    "HOD Phy / Science" => "HOD Phy & HOD Science",
    "HOD PHY" => "HOD PHY",
    "HOD PHy" => "HOD PHy",
    "HOD Phy" => "HOD Phy",
    "HOD Physic" => "HOD Physic",
    "HOD Physics KS4" => "HOD Physics KS4",
    "HOD Physics KS5" => "HOD Physics KS5",
    "HOD Physics" => "HOD Physics",
    "HOD Politics" => "HOD Politics",
    "HOD Product Design / DT" => "HOD Product Design & HOD DT",
    "HOD PSHE" => "HOD PSHE",
    "HOD PSHE, Art, Textiles & Photo" => "HOD PSHE & HOD Art & HOD Textiles & HOD Photo",
    "HOD Psy & Soc Sciences" => "HOD Psy & HOD Social Sciences",
    "HOD Psy & Soc" => "HOD Psy & HOD Soc",
    "HOD Psy" => "HOD Psy",
    "HOD Psyc" => "HOD Psyc",
    "HOD Psychology & RE" => "HOD Psychology & HOD RE",
    "HOD Psychology & Soc" => "HOD Psychology & HOD Soc",
    "HOD Psychology & Sociology" => "HOD Psychology & HOD Sociology",
    "HOD Psychology And Sociology" => "HOD Psychology & HOD Sociology",
    "HOD Psychology" => "HOD Psychology",
    "HOD Psychology/Sociology" => "HOD Psychology & HOD Sociology",
    "HOD Psyschology" => "HOD Psyschology",
    "HOD RE & Ethics" => "HOD RE & HOD Ethics",
    "HOD RE & Philosophy" => "HOD RE & HOD Philosophy",
    "HOD RE & PSHE" => "HOD RE & HOD PSHE",
    "HOD RE & Soc" => "HOD RE & HOD Soc",
    "HOD RE (maternity Leave)" => "HOD RE & maternity Leave",
    "HOD RE (Maternity)" => "HOD RE & Maternity",
    "HOD RE" => "HOD RE",
    "HOD Re" => "HOD Re",
    "HOD RE/ BS/ICT" => "HOD RE & HOD BS & HOD ICT",
    "HOD Religious Education And Citizenship" => "HOD Religious Education & HOD Citizenship",
    "HOD Religious Studies" => "HOD Religious Studies",
    "HOD Resistant Materials/Graphics" => "HOD Resistant Materials & HOD Graphics",
    "HOD RM" => "HOD RM",
    "HOD RM/PD" => "HOD RM & HOD PD",
    "HOD RS" => "HOD RS",
    "HOD RS/Psychology" => "HOD RS & HOD Psychology",
    "HOD Sci / Bio" => "HOD Sci & HOD Bio",
    "HOD Sci / Chem" => "HOD Sci & HOD Chem",
    "HOD Sci / Phy" => "HOD Sci & HOD Phy",
    "HOD SCI" => "HOD SCI",
    "HOD Sci" => "HOD Sci",
    "HOD Sciecnce" => "HOD Sciecnce",
    "HOD Science & MFL" => "HOD Science & HOD MFL",
    "HOD Science (Joint)" => "HOD Science & Joint",
    "HOD Science / Physics" => "HOD Science & HOD Physics",
    "HOD Science Acting" => "HOD Science Acting",
    "HOD Science" => "HOD Science",
    "HOD Science/Biology" => "HOD Science & HOD Biology",
    "HOD Science/HOD Biology" => "HOD Science & HOD Biology",
    "HOD Science/Physics" => "HOD Science & HOD Physics",
    "HOD Soc Sci" => "HOD Soc Sci",
    "HOD Soc" => "HOD Soc",
    "HOD Social Science" => "HOD Social Science",
    "HOD Social Sciences" => "HOD Social Sciences",
    "HOD Sociology" => "HOD Sociology",
    "HOD Spa" => "HOD Spa",
    "HOD SPAN" => "HOD SPAN",
    "HOD Span" => "HOD Span",
    "HOD Spanish" => "HOD Spanish",
    "HOD Sports" => "HOD Sports",
    "HOD Tech & Art & Design" => "HOD Tech & HOD Art & HOD Design",
    "HOD TECH" => "HOD TECH",
    "HOD Tech" => "HOD Tech",
    "HOD Technology" => "HOD Technology",
    "HOD Text" => "HOD Text",
    "HOD Textiles" => "HOD Textiles",
    "HOD Theology & Philosophy" => "HOD Theology & HOD Philosophy",
    "HOD Theology And Philosophy" => "HOD Theology And Philosophy",
    "HOD Visual & Media Arts" => "HOD Visual Arts & HOD Media Arts",
    "HOD Visual Arts" => "HOD Visual Arts",
    "HOD" => "HOD",
    "HOF Art & Technology" => "HOF Art & HOF Technology",
    "HOF Art, Design & Technology" => "HOF Art & HOF Design & HOF Technology",
    "HOF Art, DT & ICT" => "HOF Art & HOF DT & HOF ICT",
    "HOF Art, Mus & Drama" => "HOF Art & HOF Mus & HOF Drama",
    "HOF Art, Text, Photo, PD & DT" => "HOF Art & HOF Text & HOF Photo & HOF PD & HOF DT",
    "HOF Boys PE" => "HOF Boys PE",
    "HOF BS, Eco, Gov & Pol & Phil" => "HOF BS & Eco & HOF Gov & HOF Pol & HOF Phil",
    "HOF Bus & Voc Studies" => "HOF Bus & HOF Voc Studies",
    "HOF Business" => "HOF Business",
    "HOF Comp, BS, ICT, DT" => "HOF Comp & HOF BS & HOF ICT & HOF DT",
    "HOF Computing & DT" => "HOF Computing & HOF DT",
    "HOF Computing & Enterprise" => "HOF Computing & HOF Enterprise",
    "HOF Computing" => "HOF Computing",
    "HOF Creative Arts & Technology" => "HOF Creative Arts & HOF Technology",
    "HOF Creative Arts" => "HOF Creative Arts",
    "HOF Creativity" => "HOF Creativity",
    "HOF Drama & Dance" => "HOF Drama & HOF Dance",
    "HOF DT" => "HOF DT",
    "HOF Eng" => "HOF Eng",
    "HOF Eng, Drama & Music" => "HOF Eng & HOF Drama & HOF Music",
    "HOF English & Film" => "HOF English & HOF Film",
    "HOF English" => "HOF English",
    "HOF English, Drama & PE" => "HOF English & HOF Drama & HOF PE",
    "HOF Expressive Art" => "HOF Expressive Art",
    "HOF Girls PE" => "HOF Girls PE",
    "HOF HUM & MFL" => "HOF HUM & HOF MFL",
    "HOF HUM" => "HOF HUM",
    "HOF Hum" => "HOF Hum",
    "HOF Humanities & HOD Geo" => "HOF Humanities & HOD Geo",
    "HOF Languaes" => "HOF Languaes",
    "HOF Math & Comp" => "HOF Math & HOF Comp",
    "HOF Math & ICT" => "HOF Math & HOF ICT",
    "HOF Math" => "HOF Math",
    "HOF Maths" => "HOF Maths",
    "HOF Maths, Comp & Media" => "HOF Maths & HOF Comp & HOF Media",
    "HOF MFL & Hum" => "HOF MFL & HOF Hum",
    "HOF MFL" => "HOF MFL",
    "HOF MFL, BS & ICT" => "HOF MFL & HOF BS & HOF ICT",
    "HOF MFL, PE & Hum" => "HOF MFL & HOF PE & HOF Hum",
    "HOF Mus" => "HOF Mus",
    "HOF PE & PSY" => "HOF PE & HOF PSY",
    "HOF PE" => "HOF PE",
    "HOF Perf Arts" => "HOF Perf Arts",
    "HOF RE & MFL" => "HOF RE & HOF MFL",
    "HOF Sci" => "HOF Sci",
    "HOF Science" => "HOF Science",
    "HOF Science, Art & DT" => "HOF Science & HOF Art & HOF DT",
    "HOF Science, Comp, Media" => "HOF Science & HOF Comp & HOF Media",
    "HOF Scienece" => "HOF Scienece",
    "HOF Social Sciences" => "HOF Social Sciences",
    "HOF Technology" => "HOF Technology",
    "HOF Technology, & ICT" => "HOF Technology & HOF ICT",
    "HOF Visual Arts" => "HOF Visual Arts",
    "HOR MFL" => "HOR MFL",
    "HR & Office Manager" => "HR & Office Manager",
    "Hr (REC)" => "Hr & REC",
    "HR - Perm" => "HR & Perm",
    "HR - REC" => "HR & REC",
    "HR - Rec" => "HR & Rec",
    "HR / Rec" => "HR & Rec",
    "HR / Recruitment" => "HR & Recruitment",
    "HR Admin" => "HR Admin",
    "HR Advisor" => "HR Advisor",
    "HR Assistant - Recruitment" => "HR Assistant & Recruitment",
    "HR Assistant" => "HR Assistant",
    "HR Asst" => "HR Asst",
    "HR Manager & Head P/A" => "HR Manager & Head P/A",
    "HR Manager (Best Person)" => "HR Manager & Best Person",
    "HR Manager (main Contact For LTS)" => "HR Manager & main Contact For LTS",
    "HR Manager (Perm)" => "HR Manager & Perm",
    "HR Manager (REC Bishop J)" => "HR Manager & REC Bishop J",
    "HR Manager (REC)" => "HR Manager & REC",
    "HR Manager - Deals With Recruitment" => "HR Manager & Recruitment",
    "HR Manager - Recruitment" => "HR Manager & Recruitment",
    "HR Manager / Heads PA" => "HR Manager & Heads PA",
    "HR Manager For Whole Trust" => "HR Manager",
    "HR Manager" => "HR Manager",
    "HR Manager/Recruitment" => "HR Manager & HOD Recruitment",
    "HR Officer" => "HR Officer",
    "HR Person" => "HR Manager",
    "HR Team & Heads P/A" => "HR Manager & Heads P/A",
    "HR" => "HR",
    "Hr" => "Hr",
    "HR/Administration Officer" => "HR & Administration Officer",
    "HR/Recruitment" => "HR & Recruitment",
    "Humanities & MFL" => "HOD Humanities & HOD MFL",
    "ICT HOD" => "HOD ICT",
    "Inclusion Lead" => "Inclusion Lead",
    "Interim Principal" => "Interim Principal",
    "Joint Head Of Maths" => "Joint Head Of Maths",
    "Joint Head" => "Joint Head",
    "Joint HOD ADT" => "Joint HOD ADT",
    "Joint HOD Art" => "Joint HOD Art",
    "Joint HOD Drama" => "Joint HOD Drama",
    "Joint HOD Eng" => "Joint HOD Eng",
    "Joint HOD Maths" => "Joint HOD Maths",
    "Joint HOD Music" => "Joint HOD Music",
    "Joint HOD PE" => "Joint HOD PE",
    "Joint HOD Vis Art" => "Joint HOD Vis Art",
    "Managing Director" => "Managing Director",
    "Math & ICT HOD" => "HOD Math & HOD ICT",
    "Math HOD" => "HOD Math",
    "MFL HOD" => "HOD MFL",
    "Office Manager (REC)" => "Office Manager & REC",
    "Office Manager" => "Office Manager",
    "Only Drama Teacher They Have" => "Only Drama Teacher They Have",
    "Only Music Teacher They Have" => "Only Music Teacher They Have",
    "Operations Manager" => "Operations Manager",
    "Ops Director" => "Ops Director",
    "PA To Alex Lewis & HR Man" => "HR Manager",
    "Pa To Anna Richardson & HR Man" => "HR Manager",
    "PA To Head Teacher" => "Head Teacher PA",
    "PA To SLT (HR)" => "SLT PA & HR",
    "PA To SLT" => "SLT PA",
    "PA To VP" => "VP PA",
    "PA" => "PA",
    "Partnership Head Of School" => "Partnership Head Of School",
    "Personnel & Admin Man" => "Personnel & Admin Man",
    "Personnel (REC)" => "Personnel & REC",
    "Personnel / Recruitment" => "Personnel & Recruitment",
    "Personnel" => "Personnel",
    "Prin & CEO PA / Office Man" => "Office Manager",
    "Principal" => "Principal",
    "Rec (Perm)" => "Rec & Perm",
    "Rec (teacher)" => "Rec & Teacher",
    "REC - Perm" => "REC & Perm",
    "Rec Email" => "Rec Email",
    "Rec Manager / Deputy Head" => "Rec Manager & Deputy Head",
    "Rec Manager" => "Rec Manager",
    "REC Person" => "REC Person",
    "Rec Person" => "Rec Person",
    "REC" => "REC",
    "Rec" => "Rec",
    "Recruitment (D2D)" => "Recruitment & D2D",
    "Recruitment (LTS)" => "Recruitment & LTS",
    "Recruitment Co'ordinator - Cover & LTS" => "Recruitment Co'ordinator & Cover & LTS",
    "Recruitment Co'ordinator - LTS & Cover" => "Recruitment Co'ordinator & LTS & Cover",
    "Recruitment Co'ordinator" => "Recruitment Co'ordinator",
    "Recruitment Ext 233" => "Recruitment Ext 233",
    "Recruitment Manager" => "Recruitment Manager",
    "Recruitment" => "Recruitment",
    "Recruitment/HR" => "Recruitment & HR",
    "Recruitment/PA" => "Recruitment & PA",
    "School Aministrator" => "School Aministrator",
    "School Bus Manager (PERM REC)" => "School Bus Manager & PERM REC",
    "School Bus Manager" => "School Bus Manager",
    "School Business Manager" => "School Business Manager",
    "SCI HOD" => "HOD SCI",
    "Sci HOD" => "HOD Sci",
    "Science" => "Science",
    "Second Head" => "Second Head",
    "Second Master" => "Second Master",
    "SENCO" => "SENCO",
    "SENCo" => "SENCo",
    "Senco" => "Senco",
    "SENDCO" => "SENDCO",
    "SENDCo" => "SENDCo",
    "Senior Assistant Head Teacher" => "Senior Assistant Head Teacher",
    "Senior Assistant Head" => "Senior Assistant Head",
    "Senior Assistant Principal" => "Senior Assistant Principal",
    "Senior Asst Head" => "Senior Asst Head",
    "Senior Deputy Head" => "Senior Deputy Head",
    "Senior Deputy Headteacher" => "Senior Deputy Headteacher",
    "Senior Head" => "Senior Head",
    "Senior HR" => "Senior HR",
    "Senior Leader" => "Senior Leader",
    "Senior Vice Principal" => "Senior Vice Principal",
    "SLT - HR Manager (REC)" => "SLT & HR Manager & REC",
    "STEM" => "STEM",
    "Sub Master" => "Sub Master",
    "SVP" => "SVP",
    "Teaching & Learning" => "Teaching & Learning",
    "Teaching And Learning" => "Teaching & Learning",
    "The Headmistress" => "Headmistress",
    "The Principal" => "Principal",
    "Vacancies" => "Vacancies",
    "Vice Principal (rec)" => "Vice Principal & rec",
    "Vice Principal" => "Vice Principal",
    "Vice Principals" => "Vice Principals",
    "Vice" => "Vice",
    "VP" => "VP",
);

$rawPositions = array();

foreach ($combined as $combine){

    $positions = explode('&',$combine);

    $rawPositions = array_merge($positions,$rawPositions);

}

foreach ($rawPositions as $k => $pos){

    $pos = trim($pos);

    $subpos = explode(' ',$pos);
    foreach ($subpos as $l => $sub){
        if(isset($replace[$sub])){
            $subpos[$l] = $replace[$sub];
        }
    }
    $subpos = implode(' ',$subpos);

    $rawPositions[$k] = $pos;

//    echo '"'.$pos.'" => "'.$subpos.'",';
//    echo "<br>";


}



$replaced = array(
    "Acting Assistant Head Teacher" => "Acting Assistant Head Teacher",
    "Acting Asst Head" => "Acting Assistant Head",
    "Acting Deputy Head" => "Acting Deputy Head",
    "Acting Deputy Principal" => "Acting Deputy Principal",
    "Acting Head Teacher" => "Acting Head Teacher",
    "Acting Head" => "Acting Head",
    "Acting Headteacher" => "Acting Head Teacher",
    "Acting HOD Art" => "Acting HOD Arts",
    "Acting HOD BS" => "Acting HOD Business School",
    "Acting HOD Bus" => "Acting HOD Business",
    "Acting HOD DT" => "Acting HOD Design and Technology",
    "Acting HOD ECO" => "Acting HOD Economics",
    "Acting HOD Eng" => "Acting HOD English",
    "Acting HOD Fre" => "Acting HOD French",
    "Acting HOD French" => "Acting HOD French",
    "Acting HOD Geo" => "Acting HOD Geography",
    "Acting HOD Geography" => "Acting HOD Geography",
    "Acting HOD Hist" => "Acting HOD History",
    "Acting HOD Maths" => "Acting HOD Math",
    "Acting HOD MFL" => "Acting HOD Modern Foreign Languages",
    "Acting HOD Mus" => "Acting HOD Music",
    "Acting HOD PE" => "Acting HOD Physical Education",
    "Acting HOD RE" => "Acting HOD Real Estate",
    "Acting HOD Sci" => "Acting HOD Science",
    "Acting HOD Science" => "Acting HOD Science",
    "Acting Principal" => "Acting Principal",
    "Acting VP" => "Acting Vice Principal",
    "Admin Man" => "Admin Man",
    "Admin" => "Admin",
    "Administration Officer" => "Administration Officer",
    "All Recruitment" => "All Recruitment",
    "AP" => "AP",
    "Art HOD" => "Arts HOD",
    "Asistant Head" => "Assistant Head",
    "Asscoiate Asst Head" => "Associate Assistant Head",
    "Assisnat Head" => "Assistant Head",
    "Assisstant Head" => "Assistant Head",
    "Assistan Head" => "Assistant Head",
    "Assistant Bursar" => "Assistant Bursar",
    "Assistant Head Teacher" => "Assistant Head Teacher",
    "Assistant Head" => "Assistant Head",
    "Assistant Head/HOD RE" => "Assistant Head/HOD Real Estate",
    "Assistant Head/SENDCo" => "Assistant Head/SENDCo",
    "Assistant Headteacher" => "Assistant Head Teacher",
    "Assistant PA To SLT" => "Assistant Personal Assistant To ",
    "Assistant Principal" => "Assistant Principal",
    "Assistant Principals" => "Assistant Principal",
    "Assistant Vice Principal" => "Assistant Vice Principal",
    "Assistant" => "Assistant",
    "Assitant Head" => "Assitant Head",
    "Asso Ass Head" => "Associate Assistant Head",
    "Asso Asst Head" => "Associate Assistant Head",
    "Assoc Asst Head" => "Associate Assistant Head",
    "Assoc Head" => "Associate Head",
    "Associate Assistant Head" => "Associate Assistant Head",
    "Associate Assistant Headteacher" => "Associate Assistant Head Teacher",
    "Associate Assistant Principal" => "Associate Assistant Principal",
    "Associate Assit Head" => "Associate Assistant Head",
    "Associate Asst Head" => "Associate Assistant Head",
    "Associate Deputy Head" => "Associate Deputy Head",
    "ASSOCIATE HEAD TEACHER" => "Associate Head Teacher",
    "Associate Head" => "Associate Head",
    "Associate P" => "Associate Professor",
    "Associate Principal" => "Associate Principal",
    "Associate SLT Member" => "Associate Member",
    "Assstant" => "Assistant",
    "AVP" => "AVP",
    "Best Person" => "Best Person",
    "BS Manager" => "Business School Manager",
    "Bursar Assistant" => "Bursar Assistant",
    "Bursar" => "Bursar",
    "Burser" => "Bursar",
    "Bus HOD" => "Business HOD",
    "Bus Manager" => "Business Manager",
    "Business Manager" => "Business Manager",
    "Business" => "Business",
    "CEO Riverston Schools" => "CEO Riverston Schools",
    "CEO Trust" => "CEO Trust",
    "CEO Unity Schools Trust" => "CEO Unity Schools Trust",
    "CEO" => "CEO",
    "Chief Executive" => "Chief Executive",
    "CO Head" => "CO Head",
    "Co Heads" => "Co Head",
    "Co-Assistant Principal" => "Co-Assistant Principal",
    "Co-Head Teacher" => "Co-Head Teacher",
    "Comp" => "Computer",
    "Company Secretary" => "Company Secretary",
    "Cover And REC" => "Cover And Recruitment",
    "Cover Manager" => "Cover Manager",
    "Cover" => "Cover",
    "Curriculum PA" => "Curriculum Personal Assistant",
    "D2D" => "Day To Day",
    "Dance" => "Dance",
    "Day To Day" => "Day To Day",
    "Dep Rec" => "Deputy Recruitment",
    "Deputh Head" => "Deputy Head",
    "Deputy Asst Head" => "Deputy Assistant Head",
    "Deputy Head PA" => "Deputy Head Personal Assistant",
    "Deputy Head Teacher" => "Deputy Head Teacher",
    "Deputy Head" => "Deputy Head",
    "Deputy Heads PA" => "Deputy Head Personal Assistant",
    "Deputy Headteacher" => "Deputy Head Teacher",
    "Deputy Learning" => "Deputy Learning",
    "Deputy Principal" => "Deputy Principal",
    "Deputy Teaching" => "Deputy Teaching",
    "Deputy" => "Deputy",
    "Design" => "Design",
    "Director Of Business Development" => "Director Of Business Development",
    "Director Of Formation" => "Director Of Formation",
    "Director Of Humanities" => "Director Of Humanities",
    "Director Of Learning" => "Director Of Learning",
    "Director Of Music" => "Director Of Music",
    "Director Of PE" => "Director Of Physical Education",
    "Director Of Performing Arts" => "Director Of Performing Arts",
    "Director Of Science" => "Director Of Science",
    "Director Of Sport" => "Director Of Sport",
    "Director Of Sports" => "Director Of Sports",
    "Director Of Staff" => "Director Of Staff",
    "Director Of Studies" => "Director Of Studies",
    "Eco" => "Economics",
    "Exe PA" => "Executive Personal Assistant",
    "Executive Assistant" => "Executive Assistant",
    "Executive Head Teacher" => "Executive Head Teacher",
    "Executive Head" => "Executive Head",
    "Executive Principal" => "Executive Principal",
    "Executive Principle" => "Executive Principal",
    "Finance And Business Manager" => "Finance And Business Manager",
    "Finance Manager" => "Finance Manager",
    "Head Aquila" => "Head Aquila",
    "Head College VI" => "Head College VI",
    "Head Master" => "Head Master",
    "Head Of Academy" => "Head Of Academy",
    "Head Of English" => "Head Of English",
    "Head Of Perf Arts" => "Head Of Performing Arts",
    "Head Of Performing Arts" => "Head Of Performing Arts",
    "Head Of School" => "Head Of School",
    "Head Of Sci" => "Head Of Science",
    "Head Of Secondary School" => "Head Of Secondary School",
    "Head Of Senior School" => "Head Of Senior School",
    "Head Of Senior" => "Head Of Senior",
    "Head Of Seniors" => "Head Of Seniors",
    "Head Of Sixth Form" => "Head Of Sixth Form",
    "Head Of Upper" => "Head Of Upper",
    "Head Of Visual Arts" => "Head Of Visual Arts",
    "Head Orion" => "Head Orion",
    "Head P/A" => "Head Personal Assistant",
    "Head PA" => "Head Personal Assistant",
    "Head Pegasus" => "Head Pegasus",
    "Head Phoenix" => "Head Phoenix",
    "Head Teacher PA" => "Head Teacher Personal Assistant",
    "Head Teacher" => "Head Teacher",
    "Head Tecaher" => "Head Teacher",
    "HEAD" => "Head",
    "Head" => "Head",
    "Headmaster" => "Head Master",
    "Headmistress" => "Headmistress",
    "Heads P/A" => "Head Personal Assistant",
    "Heads PA And Cover" => "Head Personal Assistant And Cover",
    "Heads PA REC" => "Head Personal Assistant Recruitment",
    "Heads Pa" => "Head Pa",
    "HEADS PA" => "Head Personal Assistant",
    "Heads PA" => "Head Personal Assistant",
    "Heads" => "Head",
    "Headteacher" => "Head Teacher",
    "Headteacher's PA" => "Head Teacher Personal Assistant",
    "Hed PA" => "Hed Personal Assistant",
    "HID Hist" => "HOD History",
    "HOD Ac" => "HOD Accounts",
    "HOD Acting" => "HOD Acting",
    "HOD Art And Design" => "HOD Arts And Design",
    "HOD ART" => "HOD Arts",
    "HOD ARt" => "HOD Arts",
    "HOD Art" => "HOD Arts",
    "Hod Art" => "HOD Arts",
    "HOD ARTS" => "HOD Arts",
    "HOD Arts" => "HOD Arts",
    "HOD B/S" => "HOD Business School",
    "HOD BIo" => "HOD Biology",
    "HOD Bio" => "HOD Biology",
    "HOD Biology Joint" => "HOD Biology Joint",
    "HOD Biology" => "HOD Biology",
    "HOD Boys PE" => "HOD Boys Physical Education",
    "HOD BS" => "HOD Business School",
    "HOD Bs" => "HOD Business School",
    "HOD BUS" => "HOD Business",
    "HOD Bus" => "HOD Business",
    "HOD Business And Economics" => "HOD Business And Economics",
    "HOD Business Studies" => "HOD Business Studies",
    "HOD Business" => "HOD Business",
    "HOD CHem" => "HOD Chemistry",
    "HOD Chem" => "HOD Chemistry",
    "HOD Chemistrry" => "HOD Chemistry",
    "HOD Chemistry" => "HOD Chemistry",
    "HOD Child Care" => "HOD Child Care",
    "HOD Citi" => "HOD Citizenship",
    "HOD Citizenship" => "HOD Citizenship",
    "HOD Classics" => "HOD Classics",
    "HOD Com Sci" => "HOD Computer Science",
    "HOD Comp Sci" => "HOD Computer Science",
    "HOD Comp Sco" => "HOD Computer Sco",
    "HOD Comp" => "HOD Computer",
    "HOD Compu" => "HOD Computing",
    "HOD Computer Science" => "HOD Computer Science",
    "HOD COmputing" => "HOD Computing",
    "HOD Computing" => "HOD Computing",
    "HOD Computing, BS" => "HOD Computing, Business School",
    "HOD Construction" => "HOD Construction",
    "HOD Creat Arts" => "HOD Creative Arts",
    "HOD Creative Arts" => "HOD Creative Arts",
    "HOD Creative Technologies" => "HOD Creative Technologies",
    "HOD Creative" => "HOD Creative",
    "HOD Dance" => "HOD Dance",
    "Hod Dance" => "HOD Dance",
    "HOD Design Technology" => "HOD Design Technology",
    "HOD Design" => "HOD Design",
    "HOD Digital Technology" => "HOD Digital Technology",
    "HOD Drama And Perfoming Arts" => "HOD Drama And Performing Arts",
    "HOD Drama" => "HOD Drama",
    "HOD DT" => "HOD Design and Technology",
    "HOD Dt" => "HOD Design and Technology",
    "HOD EAL" => "HOD EAL",
    "HOD EC" => "HOD Economics",
    "HOD ECO" => "HOD Economics",
    "HOD Eco" => "HOD Economics",
    "HOD Econ" => "HOD Economics",
    "HOD Econo" => "HOD Economics",
    "HOD Economics" => "HOD Economics",
    "HOD Electronics" => "HOD Electronics",
    "HOD ENG" => "HOD English",
    "HOD Eng" => "HOD English",
    "HOD Engineering" => "HOD Engineering",
    "HOD Englis" => "HOD English",
    "HOD English Acting" => "HOD English Acting",
    "HOD English" => "HOD English",
    "HOD Englsih" => "HOD English",
    "HOD Ethics" => "HOD Ethics",
    "HOD Exp Arts" => "HOD Expressive Arts",
    "HOD Expressive Arts" => "HOD Expressive Arts",
    "HOD Fashion" => "HOD Fashion",
    "HOD Film" => "HOD Film",
    "HOD Finance" => "HOD Finance",
    "HOD FOOD" => "HOD Food",
    "HOD FOod" => "HOD Food",
    "HOD Food" => "HOD Food",
    "HOD Fre" => "HOD French",
    "HOD French" => "HOD French",
    "HOD General" => "HOD General",
    "HOD GEO" => "HOD Geography",
    "HOD GEo" => "HOD Geography",
    "HOD Geo" => "HOD Geography",
    "HOD Geography" => "HOD Geography",
    "HOD Germ" => "HOD German",
    "HOD German" => "HOD German",
    "HOD Girls PE" => "HOD Girls Physical Education",
    "HOD Gov" => "HOD Government",
    "HOD Government And Politics" => "HOD Government And Politics",
    "HOD Government" => "HOD Government",
    "HOD Graphics" => "HOD Graphics",
    "HOD Health And Social Care" => "HOD Health And Social Care",
    "HOD Health" => "HOD Health",
    "HOD His" => "HOD History",
    "HOD HIST" => "HOD History",
    "HOD Hist" => "HOD History",
    "HOD History" => "HOD History",
    "HOD Histroy" => "HOD History",
    "HOD HUM" => "HOD Humanities",
    "HOD HUm" => "HOD Humanities",
    "HOD Hum" => "HOD Humanities",
    "HOD Humaniies" => "HOD Humanities",
    "HOD Humanities" => "HOD Humanities",
    "HOD ICT And Business" => "HOD Information Communication Technology And Business",
    "HOD ICT" => "HOD Information Communication Technology",
    "HOD ICt" => "HOD Information Communication Technology",
    "HOD IT" => "HOD Information Technology",
    "HOD Italian" => "HOD Italian",
    "HOD Languages" => "HOD Languages",
    "HOD Mandarin" => "HOD Mandarin",
    "HOD Math" => "HOD Math",
    "HOD Math, BS" => "HOD Math, Business School",
    "HOD Mathematics" => "HOD Mathematics",
    "HOD Maths Acting" => "HOD Math Acting",
    "HOD MAths" => "HOD Math",
    "HOD Maths" => "HOD Math",
    "Hod Maths" => "HOD Math",
    "HOD Med" => "HOD Medicine",
    "HOD Medi" => "HOD Medicine",
    "HOD Media Arts" => "HOD Media Arts",
    "HOD Media Studies" => "HOD Media Studies",
    "HOD MEdia" => "HOD Media",
    "HOD Media" => "HOD Media",
    "HOD MFL Acting" => "HOD Modern Foreign Languages Acting",
    "HOD MFl" => "HOD MFl",
    "HOD Mfl" => "HOD Mfl",
    "HOD MFL" => "HOD Modern Foreign Languages",
    "HOD MUS" => "HOD Music",
    "HOD Mus" => "HOD Music",
    "HOD MUSIC" => "HOD Music",
    "HOD Music" => "HOD Music",
    "HOD Nutrition" => "HOD Nutrition",
    "HOD PD" => "HOD PD",
    "HOD PE" => "HOD Physical Education",
    "Hod Pe" => "HOD Physical Education",
    "HOD Pefroming Arts" => "HOD Performing Arts",
    "HOD PERF ARTS" => "HOD Performing Arts",
    "HOD PERF Arts" => "HOD Performing Arts",
    "HOD Perf Arts" => "HOD Performing Arts",
    "HOD Performing Arts" => "HOD Performing Arts",
    "HOD Philosophy" => "HOD Philosophy",
    "HOD Photo" => "HOD Photo",
    "HOD Photography" => "HOD Photography",
    "HOD PHSE" => "HOD PHSE",
    "HOD PHY" => "HOD Physics",
    "HOD PHy" => "HOD Physics",
    "HOD Phy" => "HOD Physics",
    "HOD Physic" => "HOD Physic",
    "HOD Physics KS4" => "HOD Physics KS4",
    "HOD Physics KS5" => "HOD Physics KS5",
    "HOD Physics" => "HOD Physics",
    "HOD Point" => "HOD Point",
    "HOD Pol" => "HOD Politics",
    "HOD Poli" => "HOD Politics",
    "HOD Politics" => "HOD Politics",
    "HOD Polo" => "HOD Politics",
    "HOD Product Design" => "HOD Product Design",
    "HOD PSHE" => "HOD PSHE",
    "HOD Pshe" => "HOD PSHE",
    "HOD Psy" => "HOD Psychology",
    "HOD Psyc" => "HOD Psychology",
    "HOD Psychology" => "HOD Psychology",
    "HOD Psyschology" => "HOD Psychology",
    "HOD RE" => "HOD Real Estate",
    "HOD Re" => "HOD Real Estate",
    "HOD Recruitment" => "HOD Recruitment",
    "HOD Religious Education" => "HOD Religious Education",
    "HOD Religious Studies" => "HOD Religious Studies",
    "HOD Resistant Materials" => "HOD Resistant Materials",
    "HOD RM" => "HOD Resistant Materials",
    "HOD RS" => "HOD RS",
    "HOD SC" => "HOD Social Care",
    "HOD SCI" => "HOD Science",
    "HOD Sci" => "HOD Science",
    "HOD Sciecnce" => "HOD Science",
    "HOD Science Acting" => "HOD Science Acting",
    "HOD Science" => "HOD Science",
    "HOD SENCo" => "HOD Senco",
    "HOD Soc Sci" => "HOD Sociology Science",
    "HOD Soc" => "HOD Sociology",
    "HOD Social Care" => "HOD Social Care",
    "HOD Social Science" => "HOD Social Science",
    "HOD Social Sciences" => "HOD Social Science",
    "HOD Sociology" => "HOD Sociology",
    "HOD Spa" => "HOD Spanish",
    "HOD SPAN" => "HOD Spanish",
    "HOD Span" => "HOD Spanish",
    "HOD Spanish" => "HOD Spanish",
    "HOD Sports" => "HOD Sports",
    "HOD TECH" => "HOD Technology",
    "HOD Tech" => "HOD Technology",
    "HOD Technology" => "HOD Technology",
    "HOD Text" => "HOD Textiles",
    "HOD Texties" => "HOD Textiles",
    "HOD Textiles Technology" => "HOD Textiles Technology",
    "HOD Textiles" => "HOD Textiles",
    "HOD Theology And Philosophy" => "HOD Theology And Philosophy",
    "HOD Theology" => "HOD Theology",
    "HOD Visual Arts" => "HOD Visual Arts",
    "HOD" => "HOD",
    "HOF Art" => "HOF Arts",
    "HOF Boys PE" => "HOF Boys Physical Education",
    "HOF BS" => "HOF Business School",
    "HOF Bus" => "HOF Business",
    "HOF Business" => "HOF Business",
    "HOF Cimmunications" => "HOF Communications",
    "HOF Comp" => "HOF Computer",
    "HOF Computing" => "HOF Computing",
    "HOF Creative Arts" => "HOF Creative Arts",
    "HOF Creativity" => "HOF Creativity",
    "HOF Dance" => "HOF Dance",
    "HOF Design" => "HOF Design",
    "HOF Drama" => "HOF Drama",
    "HOF DT" => "HOF Design and Technology",
    "HOF Eng" => "HOF English",
    "HOF English" => "HOF English",
    "HOF Enterprise" => "HOF Enterprise",
    "HOF Expressive Art" => "HOF Expressive Arts",
    "HOF Film" => "HOF Film",
    "HOF Girls PE" => "HOF Girls Physical Education",
    "HOF Gov" => "HOF Government",
    "HOF HUM" => "HOF Humanities",
    "HOF Hum" => "HOF Humanities",
    "HOF Humanities" => "HOF Humanities",
    "HOF ICT" => "HOF Information Communication Technology",
    "HOF Languaes" => "HOF Languages",
    "HOF Math" => "HOF Math",
    "HOF Maths" => "HOF Math",
    "HOF Media" => "HOF Media",
    "HOF MFL" => "HOF Modern Foreign Languages",
    "HOF Mus" => "HOF Music",
    "HOF Music" => "HOF Music",
    "HOF PD" => "HOF PD",
    "HOF PE" => "HOF Physical Education",
    "HOF Perf Arts" => "HOF Performing Arts",
    "HOF Phil" => "HOF Phil",
    "HOF Photo" => "HOF Photo",
    "HOF Pol" => "HOF Politics",
    "HOF PSY" => "HOF Psychology",
    "HOF RE" => "HOF Real Estate",
    "HOF Sci" => "HOF Science",
    "HOF Science" => "HOF Science",
    "HOF Scienece" => "HOF Science",
    "HOF Social Sciences" => "HOF Social Science",
    "HOF STEM" => "HOF STEM",
    "HOF Tech" => "HOF Technology",
    "HOF Technology" => "HOF Technology",
    "HOF Text" => "HOF Textiles",
    "HOF Visual Arts" => "HOF Visual Arts",
    "HOF Voc Studies" => "HOF Voc Studies",
    "HOR MFL" => "HOR Modern Foreign Languages",
    "HR Admin" => "Human Resource Admin",
    "HR Advisor" => "Human Resource Advisor",
    "HR Assistant" => "Human Resource Assistant",
    "HR Asst" => "Human Resource Assistant",
    "HR Manager" => "Human Resource Manager",
    "HR Officer" => "Human Resource Officer",
    "HR" => "Human Resource",
    "Hr" => "Human Resource",
    "Inclusion Lead" => "Inclusion Lead",
    "Interim Principal" => "Interim Principal",
    "Joint Head Of Maths" => "Joint Head Of Math",
    "Joint Head" => "Joint Head",
    "Joint HOD ADT" => "Joint HOD Audit",
    "Joint HOD Art" => "Joint HOD Arts",
    "Joint HOD Drama" => "Joint HOD Drama",
    "Joint HOD Eng" => "Joint HOD English",
    "Joint HOD Maths" => "Joint HOD Math",
    "Joint HOD Music" => "Joint HOD Music",
    "Joint HOD PE" => "Joint HOD Physical Education",
    "Joint HOD Vis Art" => "Joint HOD Visual Arts",
    "Joint" => "Joint",
    "Learning" => "Learning",
    "LTS" => "Long Term Support",
    "main Contact For LTS" => "main Contact For Long Term Support",
    "Managing Director" => "Managing Director",
    "Maternity Leave" => "Maternity Leave",
    "maternity Leave" => "maternity Leave",
    "Maternity" => "Maternity",
    "maternity" => "maternity",
    "Maths" => "Math",
    "Office Manager" => "Office Manager",
    "Only Drama Teacher They Have" => "Only Drama Teacher They Have",
    "Only Music Teacher They Have" => "Only Music Teacher They Have",
    "Operations Manager" => "Operations Manager",
    "Ops Director" => "Ops Director",
    "PA" => "Personal Assistant",
    "Partnership Head Of School" => "Partnership Head Of School",
    "PERM REC" => "Permanent Recruitment",
    "Perm Recruitment" => "Permanent Recruitment",
    "PERM" => "Permanent",
    "Perm" => "Permanent",
    "Personnel" => "Personnel",
    "Principal" => "Principal",
    "REC Bishop J" => "Recruitment Bishop J",
    "Rec Email" => "Recruitment Email",
    "Rec Manager" => "Recruitment Manager",
    "REC Person" => "Recruitment Person",
    "Rec Person" => "Recruitment Person",
    "REC" => "Recruitment",
    "Rec" => "Recruitment",
    "rec" => "Recruitment",
    "Recruitment Co'ordinator" => "Recruitment Co'ordinator",
    "Recruitment Ext 233" => "Recruitment Ext 233",
    "Recruitment Manager" => "Recruitment Manager",
    "Recruitment" => "Recruitment",
    "School Aministrator" => "School Administrator",
    "School Bus Manager" => "School Business Manager",
    "School Business Manager" => "School Business Manager",
    "Science" => "Science",
    "Second Head" => "Second Head",
    "Second Master" => "Second Master",
    "SENCO" => "Senco",
    "SENCo" => "Senco",
    "Senco" => "Senco",
    "SENDCO" => "Senco",
    "SENDCo" => "Senco",
    "Senior Assistant Head Teacher" => "Senior Assistant Head Teacher",
    "Senior Assistant Head" => "Senior Assistant Head",
    "Senior Assistant Principal" => "Senior Assistant Principal",
    "Senior Asst Head" => "Senior Assistant Head",
    "Senior Deputy Head" => "Senior Deputy Head",
    "Senior Deputy Headteacher" => "Senior Deputy Head Teacher",
    "Senior Head" => "Senior Head",
    "Senior HR" => "Senior Human Resource",
    "Senior Leader" => "Senior Leader",
    "Senior Vice Principal" => "Senior Vice Principal",
    "SLT PA" => " Personal Assistant",
    "SLT" => "",
    "Staff Rec" => "Staff Recruitment",
    "STEM" => "STEM",
    "Sub Master" => "Sub Master",
    "SVP" => "Senior Vice President",
    "Teacher" => "Teacher",
    "Teaching" => "Teaching",
    "Vacancies" => "Vacancies",
    "Vice Principal" => "Vice Principal",
    "Vice Principals" => "Vice Principal",
    "Vice" => "Vice",
    "VP PA" => "Vice Principal Personal Assistant",
    "VP" => "Vice Principal",
);
//print_r($replaced);

foreach ($replaced as $re){

    echo '"'.ucwords($re).'",';
    echo "<br>";

}

$finalPos = array(
    " Personal Assistant",
    "",
    "Acting Assistant Head Teacher",
    "Acting Assistant Head",
    "Acting Deputy Head",
    "Acting Deputy Principal",
    "Acting Head Teacher",
    "Acting Head",
    "Acting HOD Arts",
    "Acting HOD Business School",
    "Acting HOD Business",
    "Acting HOD Design And Technology",
    "Acting HOD Economics",
    "Acting HOD English",
    "Acting HOD French",
    "Acting HOD Geography",
    "Acting HOD History",
    "Acting HOD Math",
    "Acting HOD Modern Foreign Languages",
    "Acting HOD Music",
    "Acting HOD Physical Education",
    "Acting HOD Real Estate",
    "Acting HOD Science",
    "Acting Principal",
    "Acting Vice Principal",
    "Admin Man",
    "Admin",
    "Administration Officer",
    "All Recruitment",
    "AP",
    "Arts HOD",
    "Assistant Bursar",
    "Assistant Head Teacher",
    "Assistant Head",
    "Assistant Head/HOD Real Estate",
    "Assistant Head/SENDCo",
    "Assistant Personal Assistant To ",
    "Assistant Principal",
    "Assistant Vice Principal",
    "Assistant",
    "Assitant Head",
    "Associate Assistant Head Teacher",
    "Associate Assistant Head",
    "Associate Assistant Principal",
    "Associate Deputy Head",
    "Associate Head Teacher",
    "Associate Head",
    "Associate Member",
    "Associate Principal",
    "Associate Professor",
    "AVP",
    "Best Person",
    "Bursar Assistant",
    "Bursar",
    "Business HOD",
    "Business Manager",
    "Business School Manager",
    "Business",
    "CEO Riverston Schools",
    "CEO Trust",
    "CEO Unity Schools Trust",
    "CEO",
    "Chief Executive",
    "CO Head",
    "Co Head",
    "Co-Assistant Principal",
    "Co-Head Teacher",
    "Company Secretary",
    "Computer",
    "Cover And Recruitment",
    "Cover Manager",
    "Cover",
    "Curriculum Personal Assistant",
    "Dance",
    "Day To Day",
    "Deputy Assistant Head",
    "Deputy Head Personal Assistant",
    "Deputy Head Teacher",
    "Deputy Head",
    "Deputy Learning",
    "Deputy Principal",
    "Deputy Recruitment",
    "Deputy Teaching",
    "Deputy",
    "Design",
    "Director Of Business Development",
    "Director Of Formation",
    "Director Of Humanities",
    "Director Of Learning",
    "Director Of Music",
    "Director Of Performing Arts",
    "Director Of Physical Education",
    "Director Of Science",
    "Director Of Sport",
    "Director Of Sports",
    "Director Of Staff",
    "Director Of Studies",
    "Economics",
    "Executive Assistant",
    "Executive Head Teacher",
    "Executive Head",
    "Executive Personal Assistant",
    "Executive Principal",
    "Finance And Business Manager",
    "Finance Manager",
    "Head Aquila",
    "Head College VI",
    "Head Master",
    "Head Of Academy",
    "Head Of English",
    "Head Of Performing Arts",
    "Head Of School",
    "Head Of Science",
    "Head Of Secondary School",
    "Head Of Senior School",
    "Head Of Senior",
    "Head Of Seniors",
    "Head Of Sixth Form",
    "Head Of Upper",
    "Head Of Visual Arts",
    "Head Orion",
    "Head Pa",
    "Head Pegasus",
    "Head Personal Assistant And Cover",
    "Head Personal Assistant Recruitment",
    "Head Personal Assistant",
    "Head Phoenix",
    "Head Teacher Personal Assistant",
    "Head Teacher",
    "Head",
    "Headmistress",
    "Hed Personal Assistant",
    "HOD Accounts",
    "HOD Acting",
    "HOD Arts And Design",
    "HOD Arts",
    "HOD Biology Joint",
    "HOD Biology",
    "HOD Boys Physical Education",
    "HOD Business And Economics",
    "HOD Business School",
    "HOD Business Studies",
    "HOD Business",
    "HOD Chemistry",
    "HOD Child Care",
    "HOD Citizenship",
    "HOD Classics",
    "HOD Computer Science",
    "HOD Computer Sco",
    "HOD Computer",
    "HOD Computing",
    "HOD Computing, Business School",
    "HOD Construction",
    "HOD Creative Arts",
    "HOD Creative Technologies",
    "HOD Creative",
    "HOD Dance",
    "HOD Design And Technology",
    "HOD Design Technology",
    "HOD Design",
    "HOD Digital Technology",
    "HOD Drama And Performing Arts",
    "HOD Drama",
    "HOD EAL",
    "HOD Economics",
    "HOD Electronics",
    "HOD Engineering",
    "HOD English Acting",
    "HOD English",
    "HOD Ethics",
    "HOD Expressive Arts",
    "HOD Fashion",
    "HOD Film",
    "HOD Finance",
    "HOD Food",
    "HOD French",
    "HOD General",
    "HOD Geography",
    "HOD German",
    "HOD Girls Physical Education",
    "HOD Government And Politics",
    "HOD Government",
    "HOD Graphics",
    "HOD Health And Social Care",
    "HOD Health",
    "HOD History",
    "HOD Humanities",
    "HOD Information Communication Technology And Business",
    "HOD Information Communication Technology",
    "HOD Information Technology",
    "HOD Italian",
    "HOD Languages",
    "HOD Mandarin",
    "HOD Math Acting",
    "HOD Math",
    "HOD Math, Business School",
    "HOD Mathematics",
    "HOD Media Arts",
    "HOD Media Studies",
    "HOD Media",
    "HOD Medicine",
    "HOD MFl",
    "HOD Mfl",
    "HOD Modern Foreign Languages Acting",
    "HOD Modern Foreign Languages",
    "HOD Music",
    "HOD Nutrition",
    "HOD PD",
    "HOD Performing Arts",
    "HOD Philosophy",
    "HOD Photo",
    "HOD Photography",
    "HOD PHSE",
    "HOD Physic",
    "HOD Physical Education",
    "HOD Physics KS4",
    "HOD Physics KS5",
    "HOD Physics",
    "HOD Point",
    "HOD Politics",
    "HOD Product Design",
    "HOD PSHE",
    "HOD Psychology",
    "HOD Real Estate",
    "HOD Recruitment",
    "HOD Religious Education",
    "HOD Religious Studies",
    "HOD Resistant Materials",
    "HOD RS",
    "HOD Science Acting",
    "HOD Science",
    "HOD Senco",
    "HOD Social Care",
    "HOD Social Science",
    "HOD Sociology Science",
    "HOD Sociology",
    "HOD Spanish",
    "HOD Sports",
    "HOD Technology",
    "HOD Textiles Technology",
    "HOD Textiles",
    "HOD Theology And Philosophy",
    "HOD Theology",
    "HOD Visual Arts",
    "HOD",
    "HOF Arts",
    "HOF Boys Physical Education",
    "HOF Business School",
    "HOF Business",
    "HOF Communications",
    "HOF Computer",
    "HOF Computing",
    "HOF Creative Arts",
    "HOF Creativity",
    "HOF Dance",
    "HOF Design And Technology",
    "HOF Design",
    "HOF Drama",
    "HOF English",
    "HOF Enterprise",
    "HOF Expressive Arts",
    "HOF Film",
    "HOF Girls Physical Education",
    "HOF Government",
    "HOF Humanities",
    "HOF Information Communication Technology",
    "HOF Languages",
    "HOF Math",
    "HOF Media",
    "HOF Modern Foreign Languages",
    "HOF Music",
    "HOF PD",
    "HOF Performing Arts",
    "HOF Phil",
    "HOF Photo",
    "HOF Physical Education",
    "HOF Politics",
    "HOF Psychology",
    "HOF Real Estate",
    "HOF Science",
    "HOF Social Science",
    "HOF STEM",
    "HOF Technology",
    "HOF Textiles",
    "HOF Visual Arts",
    "HOF Voc Studies",
    "HOR Modern Foreign Languages",
    "Human Resource Admin",
    "Human Resource Advisor",
    "Human Resource Assistant",
    "Human Resource Manager",
    "Human Resource Officer",
    "Human Resource",
    "Inclusion Lead",
    "Interim Principal",
    "Joint Head Of Math",
    "Joint Head",
    "Joint HOD Arts",
    "Joint HOD Audit",
    "Joint HOD Drama",
    "Joint HOD English",
    "Joint HOD Math",
    "Joint HOD Music",
    "Joint HOD Physical Education",
    "Joint HOD Visual Arts",
    "Joint",
    "Learning",
    "Long Term Support",
    "Main Contact For Long Term Support",
    "Managing Director",
    "Maternity Leave",
    "Maternity",
    "Math",
    "Office Manager",
    "Only Drama Teacher They Have",
    "Only Music Teacher They Have",
    "Operations Manager",
    "Ops Director",
    "Partnership Head Of School",
    "Permanent Recruitment",
    "Permanent",
    "Personal Assistant",
    "Personnel",
    "Principal",
    "Recruitment Bishop J",
    "Recruitment Co'ordinator",
    "Recruitment Email",
    "Recruitment Ext 233",
    "Recruitment Manager",
    "Recruitment Person",
    "Recruitment",
    "School Administrator",
    "School Business Manager",
    "Science",
    "Second Head",
    "Second Master",
    "Senco",
    "Senior Assistant Head Teacher",
    "Senior Assistant Head",
    "Senior Assistant Principal",
    "Senior Deputy Head Teacher",
    "Senior Deputy Head",
    "Senior Head",
    "Senior Human Resource",
    "Senior Leader",
    "Senior Vice President",
    "Senior Vice Principal",
    "Staff Recruitment",
    "STEM",
    "Sub Master",
    "Teacher",
    "Teaching",
    "Vacancies",
    "Vice Principal Personal Assistant",
    "Vice Principal",
    "Vice",
);
print_r($finalPos);